apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - release.yaml
configMapGenerator:
  - name: crossplane-core-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
