## WARNING: Before upgrading to influxdb v2 - Please ensure K6 supports v2. See below github issue.
## https://github.com/k6io/k6/issues/1730
## https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/Chart.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-core
spec:
  releaseName: crossplane-core
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
      version: "1.20.0-rc.0.43.gf5d7f90ee"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: crossplane-core-values
