apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: influxdb
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/dev/influxdb
  prune: true
